In [132]:
import numpy as np

In [133]:
dates = np.arange(3)

In [134]:
dates2 = np.linspace(0,2,3)

In [135]:
dates3 = np.array([np.arange(0,6),np.arange(0,6)])

In [136]:

print(dates, dates2)
print(dates3)
print(len(dates3), dates3.ndim)


[0 1 2] [0. 1. 2.]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]
2 2
