In [69]:
import random

import numpy as np

In [70]:
arr = np.arange(0,8, dtype=int)

print(arr)

[0 1 2 3 4 5 6 7]


In [71]:
arr2 = np.linspace(1.2,2.0,5)
print(arr2)

[1.2 1.4 1.6 1.8 2. ]


In [72]:
arr3 = np.array(['mary','john','peter', 'christine'])
print(arr3)

['mary' 'john' 'peter' 'christine']


In [73]:
# noinspection PyTypeChecker
arr4 = np.arange('2017-10-01','2017-11-01', dtype='datetime64[D]')
print(arr4)

['2017-10-01' '2017-10-02' '2017-10-03' '2017-10-04' '2017-10-05'
 '2017-10-06' '2017-10-07' '2017-10-08' '2017-10-09' '2017-10-10'
 '2017-10-11' '2017-10-12' '2017-10-13' '2017-10-14' '2017-10-15'
 '2017-10-16' '2017-10-17' '2017-10-18' '2017-10-19' '2017-10-20'
 '2017-10-21' '2017-10-22' '2017-10-23' '2017-10-24' '2017-10-25'
 '2017-10-26' '2017-10-27' '2017-10-28' '2017-10-29' '2017-10-30'
 '2017-10-31']


In [74]:
arr5 = np.random.rand(1,10)
print(arr5)

[[0.61533709 0.70598449 0.3747892  0.60229547 0.72911269 0.68316203
  0.73388969 0.09573962 0.58157651 0.24678372]]


In [75]:
arr6 = np.random.randint(100,200,20)
print(arr6)

[198 138 127 126 113 135 123 150 170 123 164 175 121 189 146 136 128 170
 175 106]


In [76]:
arr7 = np.linspace(5,10,50)
print(arr7)

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ]


In [77]:
arr8 = np.array([(1,2,3,4), (5,6,7,8)])
print(arr8)

[[1 2 3 4]
 [5 6 7 8]]


In [78]:
arr9 = np.zeros([3,4])
print(arr9)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [79]:
arr10 = np.full([5,5],1)
print(arr10)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [80]:
arr11 = np.full([4,3],10.5)
print(arr11)

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]]


In [81]:
arr12 = np.identity(4)
print(arr12)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [82]:
arr13 = np.around((np.random.uniform(1,6,(4,8))),2)
print(arr13)

[[3.11 2.19 5.51 5.99 1.24 5.66 3.32 2.29]
 [3.07 4.03 1.37 5.38 4.78 2.2  3.02 2.52]
 [2.5  5.91 4.88 2.94 4.29 1.54 1.8  4.75]
 [3.43 1.66 5.58 3.34 1.46 5.83 3.94 4.92]]


In [83]:
arr14 = np.empty([5,6,7])
print(arr14)

[[[ 1.30870525e-311  1.30870042e-311  2.64980517e+180  1.90886933e+136
    3.95813353e+257  4.85178805e+021  7.69316580e+218]
  [ 1.94812178e-022  1.25013738e+243  7.48956328e+247  4.17321864e+199
    1.70562045e+161  4.41854587e+257  4.84865702e+199]
  [ 6.00735883e-067  2.01247465e-022  6.94157041e+228  1.70168728e+214
    2.46112019e+242  9.83167631e+165  1.56544978e-076]
  [ 7.34058388e+223  4.36361906e+242  1.32319299e+199  1.40157949e+012
    2.26584136e+276  1.56544978e-076  7.34058388e+223]
  [ 5.88242065e+025  4.84886969e-023  2.38296654e+006  5.48271264e-086
    4.43352822e+025  1.70658590e+093  5.48430220e-086]
  [ 2.17315421e+016  2.51230852e+093  1.08216480e+045  1.51499183e-013
    3.18302720e+088  1.49838352e+151  9.94008558e+044]]

 [[ 1.44454662e+214  1.71201117e+214  2.64982496e+180  2.19096916e+252
    3.04229617e-067  1.87315672e-309  1.30870525e-311]
  [ 1.30870042e-311  1.30870525e-311 -3.48042021e-311  1.65159587e+093
    6.01207236e-067  1.42512218e+064  1.90887

In [84]:
arr15 = np.array([1.55,1.73,1.9,1.72,1.66,1.8])
arr16 = np.array\
    (
        [
            ('red', 'green', 'yellow', 'blue'),
            (True,False, False, True),
            ('2017-10-01', '2017-11-11', '2017-12-23', '2018-03-31')
        ]
    )
arr17 = np.array(
                    [
                        [
                            (10,9,8,7),
                             (6,5,4,3)
                        ],
                        [
                            (1,2,3,4),
                            (5,6,7,8)
                        ]
                    ]
                )
print(arr17.dtype)

int32


In [85]:
a = np.array([ 	['Mary',	'John',	'Bob'],
               	['Zoe', 	'Chris',	'Ann'],
               	['Leon', 'Kathy','Sam']])
b = a.flatten()
print(b)

['Mary' 'John' 'Bob' 'Zoe' 'Chris' 'Ann' 'Leon' 'Kathy' 'Sam']


In [86]:
arr18 = np.arange(15,30).reshape(3,5)
print(arr18)

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [87]:
b = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
arr = np.concatenate(b)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [88]:
a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
print(a)
print('\n')
arr = np.transpose(a)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [89]:
a = np.array([[ 1,2,3],[ 4,5,6],[7,8,9]])
b = np.full((3,3),1.5)
c = np.arange(0,15).reshape(5,3)
print(np.concatenate([a,b,c]))

[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 0.   1.   2. ]
 [ 3.   4.   5. ]
 [ 6.   7.   8. ]
 [ 9.  10.  11. ]
 [12.  13.  14. ]]


In [90]:
a = np.array([[ 1,2,3,4],[ 4,5,6,7],[7,8,9,10],[11,12,13,14]])
b = np.random.randint(10,20,(4,6))
c = np.arange(0,16).reshape(4,4 )
arr = []

for i in range(len(a)):
    arr.append(list((np.concatenate([a[i],b[i],c[i]]))))


newarr = np.array(arr)
print(newarr)

[[ 1  2  3  4 11 19 18 16 18 17  0  1  2  3]
 [ 4  5  6  7 15 14 11 18 12 17  4  5  6  7]
 [ 7  8  9 10 13 12 16 17 16 16  8  9 10 11]
 [11 12 13 14 17 17 17 19 19 13 12 13 14 15]]


In [91]:
arr_1 = np.random.randint(100,200,10)
print(arr_1)
print(np.sort(arr_1))

[175 145 113 169 153 159 184 140 171 167]
[113 140 145 153 159 167 169 171 175 184]
