In [934]:
import numpy as np

arr_2 = np.random.randint(1,20,(3,5))

print(arr_2)

arr_3 = np.sort(arr_2,axis=0)

print(arr_3)

[[ 7  1  9 14  9]
 [ 4 16 13 13 16]
 [12  8  8 18  9]]
[[ 4  1  8 13  9]
 [ 7  8  9 14  9]
 [12 16 13 18 16]]


In [935]:
arr_3 = np.random.randint(100,200,(2,5))
arr_4 = np.copy(arr_3)

print(arr_3)

arr_5 = np.sort(arr_4,axis=1)
print(arr_4)
print(arr_5)


[[174 177 109 146 124]
 [162 177 143 177 154]]
[[174 177 109 146 124]
 [162 177 143 177 154]]
[[109 124 146 174 177]
 [143 154 162 177 177]]


In [936]:
a = np.arange(1,100,1)
b = np.array([[1,2,3,4], [100,200,300,400],  [5,6,7,8],  [9,10,11,12] ])

print(a)
print(b)

c = np.transpose(np.copy(b))

print(c[-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[[  1   2   3   4]
 [100 200 300 400]
 [  5   6   7   8]
 [  9  10  11  12]]
[  4 400   8  12]


In [937]:
print(np.arange(100).reshape(5,20))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [938]:
a = np.arange(8).reshape(2,2,2)
print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [939]:
a = np.arange(8).reshape(2,4)
b = np.random.randint(20,30,(2,5))
c = np.arange(9,15).reshape(2,3)
d = np.concatenate((a,b,c),axis=1)
print(d)

[[ 0  1  2  3 23 21 26 21 24  9 10 11]
 [ 4  5  6  7 28 28 22 29 23 12 13 14]]


In [940]:
a = np.array([[ 1,2,3,4],[ 4,5,6,7],[7,8,9,10],[11,12,13,14]])
b = np.random.randint(10,20,(4,6))
c = np.arange(0,16).reshape(4,4 )
print(np.concatenate((a,b,c),axis=1))

[[ 1  2  3  4 12 17 15 18 13 15  0  1  2  3]
 [ 4  5  6  7 13 15 17 13 11 15  4  5  6  7]
 [ 7  8  9 10 11 15 16 12 18 19  8  9 10 11]
 [11 12 13 14 14 15 19 13 14 14 12 13 14 15]]


In [941]:
b = np.arange(9.).reshape(3, 3)
b5 = ( b > 5 )
print(b)
print(b5)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[False False False]
 [False False False]
 [ True  True  True]]


In [942]:
b = np.arange(24).reshape(2,3,4)
print(b)
print(b[:,0,0])
print(b[0,1,:])
print(b[:,1,:])
print(b[0,:,-1])
print(b[0,::-1,-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0 12]
[4 5 6 7]
[[ 4  5  6  7]
 [16 17 18 19]]
[ 3  7 11]
[11  7  3]


In [943]:
a = np.arange(6).reshape(2,3)
even = np.where(a % 2 == 0)
print(even)

(array([0, 0, 1], dtype=int64), array([0, 2, 1], dtype=int64))


In [944]:
x =[1, True, None, ["word", 123], "test"]
print(x[2:])

[None, ['word', 123], 'test']


In [945]:
a = np.arange(1,21).reshape(4,5)
print(a)
b = np.cumsum(a, axis=0)
print(b)
c = np.cumsum(a,axis=1)
print(c)
d = np.cumprod(a,axis=0)
e = np.cumprod(a,axis=1)
print(d)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 7  9 11 13 15]
 [18 21 24 27 30]
 [34 38 42 46 50]]
[[ 1  3  6 10 15]
 [ 6 13 21 30 40]
 [11 23 36 50 65]
 [16 33 51 70 90]]
[[    1     2     3     4     5]
 [    6    14    24    36    50]
 [   66   168   312   504   750]
 [ 1056  2856  5616  9576 15000]]
[[      1       2       6      24     120]
 [      6      42     336    3024   30240]
 [     11     132    1716   24024  360360]
 [     16     272    4896   93024 1860480]]


In [946]:
filename = "../SGresidents.csv"
data = np.genfromtxt(filename, dtype=['i2', 'U50', 'i8'],
                     delimiter=',', names=True)
# print(data[:5]) #peep into data
print(f'There are altogether {len(data)} rows in the data file {filename}.\n')
keyword = 'Total Residents'
totalresidents = data[data['level_1']==keyword]

max = totalresidents['value'].argmax()
print(totalresidents[max]['year'])

min = totalresidents['value'].min()
min_index = totalresidents['value'].argmin()
print(min,totalresidents[min_index]['year'], totalresidents[min_index]['level_1'])

There are altogether 855 rows in the data file ../SGresidents.csv.

2016
1646400 1960 Total Residents


In [947]:
a = np.arange(10,50,0.5)
b = np.arange(10,20,0.1)

print(np.std(a).round(2),np.std(b).round(2),np.var(a).round(2),np.var(b).round(2)) 

11.55 2.89 133.31 8.33


In [948]:
a = np.random.randint(1,1000,(3,4))
print(a)
print(np.max(a,axis=1))
print(np.max(a))
print('Location of maximum value:',np.unravel_index(np.argmax(a),a.shape))
print(np.min(a,axis=1))
print(np.min(a))
print('Location of maximum value:',np.unravel_index(np.argmin(a),a.shape))

[[ 30 635 820  86]
 [270 337 238 919]
 [252  24 134 852]]
[820 919 852]
919
Location of maximum value: (1, 3)
[ 30 238  24]
24
Location of maximum value: (2, 1)
